@startuml
title 読書感想システム

actor ユーザ
actor 管理者

left to right direction
rectangle 読書感想システム {
    package 利用側 {
        ユーザ --> (アカウントを登録する)
        ユーザ --> (アカウントを更新する)
        ユーザ --> (アカウントを削除する)
        ユーザ --> (読書感想を一覧)
        ユーザ --> (読書感想を登録)
        ユーザ --> (読書感想を更新)
        ユーザ --> (読書感想を削除)
        ユーザ --> (他人の読書感想を一覧)
        ユーザ --> (他人の読書感想を参照)
        ユーザ --> (他人の読書感想をいいね)
        ユーザ --> (他人の読書感想をいいね削除)
    }
    package 管理側 {
        (本の名前を名寄せ[管理]) <-- 管理者
        (ユーザを一覧[管理]) <-- 管理者
        (ユーザを削除[管理]) <-- 管理者
        (読書感想を一覧[管理]) <-- 管理者
        (読書感想を削除[管理]) <-- 管理者
    }
}
@enduml